//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTestStation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RelayCom1 {
            get {
                return ((int)(this["RelayCom1"]));
            }
            set {
                this["RelayCom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RelayCom2 {
            get {
                return ((int)(this["RelayCom2"]));
            }
            set {
                this["RelayCom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HasRelay {
            get {
                return ((bool)(this["HasRelay"]));
            }
            set {
                this["HasRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HasMultimeter {
            get {
                return ((bool)(this["HasMultimeter"]));
            }
            set {
                this["HasMultimeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int MultimeterDelay {
            get {
                return ((int)(this["MultimeterDelay"]));
            }
            set {
                this["MultimeterDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TemperatureRefreshInterval {
            get {
                return ((int)(this["TemperatureRefreshInterval"]));
            }
            set {
                this["TemperatureRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ChartTemperatureMin {
            get {
                return ((double)(this["ChartTemperatureMin"]));
            }
            set {
                this["ChartTemperatureMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double ChartTemperatureMax {
            get {
                return ((double)(this["ChartTemperatureMax"]));
            }
            set {
                this["ChartTemperatureMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.9")]
        public double ChartChargingVoltageMin {
            get {
                return ((double)(this["ChartChargingVoltageMin"]));
            }
            set {
                this["ChartChargingVoltageMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.2")]
        public double ChartChargingVoltageMax {
            get {
                return ((double)(this["ChartChargingVoltageMax"]));
            }
            set {
                this["ChartChargingVoltageMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ChartChargingCurrentMin {
            get {
                return ((double)(this["ChartChargingCurrentMin"]));
            }
            set {
                this["ChartChargingCurrentMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double ChartChargingCurrentMax {
            get {
                return ((double)(this["ChartChargingCurrentMax"]));
            }
            set {
                this["ChartChargingCurrentMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2E-06")]
        public double ChartDischargeCurrentMin {
            get {
                return ((double)(this["ChartDischargeCurrentMin"]));
            }
            set {
                this["ChartDischargeCurrentMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5E-06")]
        public double ChartDischargeCurrentMax {
            get {
                return ((double)(this["ChartDischargeCurrentMax"]));
            }
            set {
                this["ChartDischargeCurrentMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.0001")]
        public double ChartDischargeVoltageMin {
            get {
                return ((double)(this["ChartDischargeVoltageMin"]));
            }
            set {
                this["ChartDischargeVoltageMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0005")]
        public double ChartDischargeVoltageMax {
            get {
                return ((double)(this["ChartDischargeVoltageMax"]));
            }
            set {
                this["ChartDischargeVoltageMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.05")]
        public double ChartOpenCircuitVoltageMin {
            get {
                return ((double)(this["ChartOpenCircuitVoltageMin"]));
            }
            set {
                this["ChartOpenCircuitVoltageMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double ChartOpenCircuitVoltageMax {
            get {
                return ((double)(this["ChartOpenCircuitVoltageMax"]));
            }
            set {
                this["ChartOpenCircuitVoltageMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ChartCumulativeIntegralMin {
            get {
                return ((double)(this["ChartCumulativeIntegralMin"]));
            }
            set {
                this["ChartCumulativeIntegralMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.12")]
        public double ChartCumulativeIntegralMax {
            get {
                return ((double)(this["ChartCumulativeIntegralMax"]));
            }
            set {
                this["ChartCumulativeIntegralMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.0005")]
        public double ChartCurrentIntegralMin {
            get {
                return ((double)(this["ChartCurrentIntegralMin"]));
            }
            set {
                this["ChartCurrentIntegralMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.003")]
        public double ChartCurrentIntegralMax {
            get {
                return ((double)(this["ChartCurrentIntegralMax"]));
            }
            set {
                this["ChartCurrentIntegralMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ChartImpedanceMin {
            get {
                return ((double)(this["ChartImpedanceMin"]));
            }
            set {
                this["ChartImpedanceMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double ChartImpedanceMax {
            get {
                return ((double)(this["ChartImpedanceMax"]));
            }
            set {
                this["ChartImpedanceMax"] = value;
            }
        }
    }
}
